name: Full CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mock-api:
    uses: ./.github/workflows/mock-api.yml
  
  api:
    uses: ./.github/workflows/api.yml
  
  ios:
    uses: ./.github/workflows/ios.yml