name: iOS CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        
      - name: List available simulators (debug)
        run: xcrun simctl list devices
        
      - name: Build and test iOS app
        run: |
          cd apps/ios/GeoTrackerClient
          xcodebuild test \
            -scheme GeoTrackerClient \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -enableCodeCoverage YES \
            -skipPackagePluginValidation
            